version: '3.1'
services:
  create-metadata-bucket:
    image: jpbarto/boto3
    volumes:
      - ./images/docker-spark/master/runTasks.py:/runTasks.py
    environment:
      AWS_ACCESS_KEY_ID: cluesoKey1
      AWS_SECRET_ACCESS_KEY: cluesoSecretKey1
    entrypoint: /usr/local/bin/python /runTasks.py
    depends_on:
      - lb

  s3-front:
    build: ./images/S3/
    ports:
      - "8001:8001"
    environment:
      ENDPOINT: "localhost"
      RECORDLOG_ENABLED: "true"
    command: S3BACKEND=mem npm start

  lb:
    image: zenko/loadbalancer
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: "s3-front:8001"
    depends_on:
      - s3-front
